[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv

build_flags = 
	-I include
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_USE_DRAW_SW_ASM=0

lib_deps = 
	4-20ma/ModbusMaster@^2.0.1
	moononournation/GFX Library for Arduino@^1.4.9 ; Pastikan versi terbaru
	lvgl/lvgl@^9.2.2