[env:esp32-s3-devkitc-1]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv

build_flags = 
	-I include
	-D LV_CONF_INCLUDE_SIMPLE
	-D BOARD_HAS_PSRAM               ; Beri tahu compiler bahwa board punya PSRAM
	-mfix-esp32-psram-cache-issue    ; Memperbaiki bug glitch memori bawaan ESP32

lib_deps = 
	4-20ma/ModbusMaster@^2.0.1
	lvgl/lvgl@^8.4.0